
@API_URL = {{$dotenv PRODUCTION_API}}

get {{API_URL}}/notes
###
Post {{API_URL}}/notes/2
Content-Type: application/json

{
    "text": "Post funkar"
}

### Uppdatera note
PUT {{API_URL}}/notes/3
Content-Type: application/json

{
    "text": "Ny text!!"
}

### Uppdatera note
DELETE {{API_URL}}/notes/2