
#@API_URL = {{$dotenv PRODUCTION_API}}
@API_URL = {{$dotenv API_URL}}

get {{API_URL}}/notes

### skapa ny note
Post {{API_URL}}/notes
Content-Type: application/json

{
    "note": "Post funkar"
}

### Uppdatera note
PUT {{API_URL}}/notes/3
Content-Type: application/json

{
    "note": "Ny text!!"
}

### Uppdatera note
DELETE {{API_URL}}/notes/2